name: Website Test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies (main)
        run: npm ci

      - name: Install dependencies (website)
        working-directory: ./website
        run: npm ci

      - name: Build website
        working-directory: ./website
        run: npm run build
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
